fail_fast: false

repos:
#-----------------------------------------------------
# General
#-----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

      # TODO: Uncomment this after initial main setup
      # - id: no-commit-to-branch

#-----------------------------------------------------
# Terraform
#-----------------------------------------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        name: Format Terraform Configuration

      - id: terraform_tflint
        name: TFLint evaluation
        args:
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_unused_required_providers'
          - '--args=--only=terraform_workspace_remote'

      - id: terraform_validate
        name: Terraform Validate
        args:
          - --hook-config=--retry-once-with-cleanup=true

      - id: terraform_providers_lock
        name: Generate lock files for CI
        args:
            - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
            - --args=-platform=linux_amd64
            - --args=-platform=darwin_arm64

      - id: terraform_docs
        name: Generate Terraform README files
        args:
          - "--args=--config=.terraform-docs.yml"
          - "--args=--lockfile=false"
          - --hook-config=--create-file-if-not-exist=true

#-----------------------------------------------------
# Shell Scripts
#-----------------------------------------------------
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt

# TODO: Add Renovate config validator when renovate.json is set up
# #-----------------------------------------------------
# # Renovate
# #-----------------------------------------------------
#   - repo: https://github.com/renovatebot/pre-commit-hooks
#     rev: 42.22.0
#     hooks:
#       - id: renovate-config-validator
